version: '3.8'
services:
    mongo:
        container_name: mongo-demo
        image: mongo:7.0
        environment:
            MONGO_INITDB_ROOT_USERNAME: mongoadmin
            MONGO_INITDB_ROOT_PASSWORD: mongodb
        ports:
            - 27018:27017
        volumes:
            - mongodata:/data/db
volumes:
    mongodata:
        driver: local
