version: '3'

services:
    mysql:
        environment:
            - MYSQL_ROOT_PASSWORD=123456
            - MYSQL_USER=gvrs
            - MYSQL_PASSWORD=123456
            - MYSQL_DATABASE=gvrs_db
            - TZ=Asia/Kolkata
        command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-time-zone=+05:30']
        container_name: mysql
        image: mysql:8.1
        volumes:
            - mysql_volume:/var/lib/mysql
        ports:
            - 3307:3306
        networks:
            - mysql_network

volumes:
    mysql_volume:

networks:
    mysql_network:
